language: node_js

node_js:
  - 8
  - 6
  - 4

install: 
  - yarn

cache:
  directories:
    - node_modules

after_success:
  - yarn run coverage
  - ./node_modules/.bin/codecov --file=./coverage/lcov.info
